# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'image.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(545, 630)
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK JP")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.board = QtWidgets.QLabel(self.centralwidget)
        self.board.setGeometry(QtCore.QRect(10, 10, 533, 578))
        self.board.setText("")
        self.board.setPixmap(QtGui.QPixmap("../images/board_v1.png"))
        self.board.setObjectName("board")
        self.silver_black = QtWidgets.QLabel(self.centralwidget)
        self.silver_black.setGeometry(QtCore.QRect(229, 459, 97, 106))
        self.silver_black.setObjectName("silver_black")
        self.silver_white = QtWidgets.QLabel(self.centralwidget)
        self.silver_white.setGeometry(QtCore.QRect(229, 35, 97, 106))
        self.silver_white.setObjectName("silver_white")
        self.king_black = QtWidgets.QLabel(self.centralwidget)
        self.king_black.setGeometry(QtCore.QRect(35, 459, 97, 106))
        self.king_black.setObjectName("king_black")
        self.king_white = QtWidgets.QLabel(self.centralwidget)
        self.king_white.setGeometry(QtCore.QRect(423, 35, 97, 106))
        self.king_white.setObjectName("king_white")
        self.gold_black = QtWidgets.QLabel(self.centralwidget)
        self.gold_black.setGeometry(QtCore.QRect(132, 459, 97, 106))
        self.gold_black.setObjectName("gold_black")
        self.gold_white = QtWidgets.QLabel(self.centralwidget)
        self.gold_white.setGeometry(QtCore.QRect(326, 35, 97, 106))
        self.gold_white.setObjectName("gold_white")
        self.bishop_black = QtWidgets.QLabel(self.centralwidget)
        self.bishop_black.setGeometry(QtCore.QRect(326, 459, 97, 106))
        self.bishop_black.setObjectName("bishop_black")
        self.bishop_white = QtWidgets.QLabel(self.centralwidget)
        self.bishop_white.setGeometry(QtCore.QRect(132, 35, 97, 106))
        self.bishop_white.setObjectName("bishop_white")
        self.rook_black = QtWidgets.QLabel(self.centralwidget)
        self.rook_black.setGeometry(QtCore.QRect(423, 459, 97, 106))
        self.rook_black.setObjectName("rook_black")
        self.rook_white = QtWidgets.QLabel(self.centralwidget)
        self.rook_white.setGeometry(QtCore.QRect(35, 35, 97, 106))
        self.rook_white.setObjectName("rook_white")
        self.pawn_black = QtWidgets.QLabel(self.centralwidget)
        self.pawn_black.setGeometry(QtCore.QRect(35, 353, 97, 106))
        self.pawn_black.setObjectName("pawn_black")
        self.pawn_white = QtWidgets.QLabel(self.centralwidget)
        self.pawn_white.setGeometry(QtCore.QRect(423, 141, 97, 106))
        self.pawn_white.setObjectName("pawn_white")
        self.board_column = QtWidgets.QLabel(self.centralwidget)
        self.board_column.setGeometry(QtCore.QRect(35, 12, 485, 19))
        self.board_column.setText("")
        self.board_column.setPixmap(QtGui.QPixmap("../images/number_v1_485_19.png"))
        self.board_column.setObjectName("board_column")
        self.board_row = QtWidgets.QLabel(self.centralwidget)
        self.board_row.setGeometry(QtCore.QRect(522, 35, 22, 530))
        self.board_row.setText("")
        self.board_row.setPixmap(QtGui.QPixmap("../images/number_v1_22_530.png"))
        self.board_row.setObjectName("board_row")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 545, 37))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menuBar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK JP")
        self.actionExit.setFont(font)
        self.actionExit.setObjectName("actionExit")
        self.actionSetting = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK JP")
        self.actionSetting.setFont(font)
        self.actionSetting.setObjectName("actionSetting")
        self.menu.addAction(self.actionExit)
        self.menu_2.addAction(self.actionSetting)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "画像のテスト"))
        self.silver_black.setText(_translate("MainWindow", "先手の銀"))
        self.silver_white.setText(_translate("MainWindow", "後手の銀"))
        self.king_black.setText(_translate("MainWindow", "先手の王"))
        self.king_white.setText(_translate("MainWindow", "後手の王"))
        self.gold_black.setText(_translate("MainWindow", "先手の金"))
        self.gold_white.setText(_translate("MainWindow", "後手の金"))
        self.bishop_black.setText(_translate("MainWindow", "先手の角"))
        self.bishop_white.setText(_translate("MainWindow", "後手の角"))
        self.rook_black.setText(_translate("MainWindow", "先手の飛"))
        self.rook_white.setText(_translate("MainWindow", "後手の飛"))
        self.pawn_black.setText(_translate("MainWindow", "先手の歩"))
        self.pawn_white.setText(_translate("MainWindow", "後手の歩"))
        self.menu.setTitle(_translate("MainWindow", "ファイル"))
        self.menu_2.setTitle(_translate("MainWindow", "設定"))
        self.actionExit.setText(_translate("MainWindow", "終了"))
        self.actionSetting.setText(_translate("MainWindow", "表示設定"))

