# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setting.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_settingWindow(object):
    def setupUi(self, settingWindow):
        settingWindow.setObjectName("settingWindow")
        settingWindow.resize(520, 540)
        self.groupBoxBoard = QtWidgets.QGroupBox(settingWindow)
        self.groupBoxBoard.setGeometry(QtCore.QRect(10, 10, 340, 140))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK JP")
        self.groupBoxBoard.setFont(font)
        self.groupBoxBoard.setObjectName("groupBoxBoard")
        self.radioButtonBoardV1 = QtWidgets.QRadioButton(self.groupBoxBoard)
        self.radioButtonBoardV1.setGeometry(QtCore.QRect(20, 40, 140, 38))
        self.radioButtonBoardV1.setObjectName("radioButtonBoardV1")
        self.buttonGroupBoard = QtWidgets.QButtonGroup(settingWindow)
        self.buttonGroupBoard.setObjectName("buttonGroupBoard")
        self.buttonGroupBoard.addButton(self.radioButtonBoardV1)
        self.radioButtonBoardV2 = QtWidgets.QRadioButton(self.groupBoxBoard)
        self.radioButtonBoardV2.setGeometry(QtCore.QRect(180, 40, 140, 38))
        self.radioButtonBoardV2.setObjectName("radioButtonBoardV2")
        self.buttonGroupBoard.addButton(self.radioButtonBoardV2)
        self.labelBoardV1 = QtWidgets.QLabel(self.groupBoxBoard)
        self.labelBoardV1.setGeometry(QtCore.QRect(20, 80, 100, 50))
        self.labelBoardV1.setText("")
        self.labelBoardV1.setPixmap(QtGui.QPixmap("../images/setting_dialog/board_image_ver_1.png"))
        self.labelBoardV1.setObjectName("labelBoardV1")
        self.labelBoardV2 = QtWidgets.QLabel(self.groupBoxBoard)
        self.labelBoardV2.setGeometry(QtCore.QRect(180, 80, 100, 50))
        self.labelBoardV2.setText("")
        self.labelBoardV2.setPixmap(QtGui.QPixmap("../images/setting_dialog/board_image_ver_2.png"))
        self.labelBoardV2.setObjectName("labelBoardV2")
        self.groupBoxPiece = QtWidgets.QGroupBox(settingWindow)
        self.groupBoxPiece.setGeometry(QtCore.QRect(10, 170, 490, 140))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK JP")
        self.groupBoxPiece.setFont(font)
        self.groupBoxPiece.setObjectName("groupBoxPiece")
        self.radioButtonPieceV1 = QtWidgets.QRadioButton(self.groupBoxPiece)
        self.radioButtonPieceV1.setGeometry(QtCore.QRect(20, 40, 140, 38))
        self.radioButtonPieceV1.setObjectName("radioButtonPieceV1")
        self.buttonGroupPiece = QtWidgets.QButtonGroup(settingWindow)
        self.buttonGroupPiece.setObjectName("buttonGroupPiece")
        self.buttonGroupPiece.addButton(self.radioButtonPieceV1)
        self.radioButtonPieceV2 = QtWidgets.QRadioButton(self.groupBoxPiece)
        self.radioButtonPieceV2.setGeometry(QtCore.QRect(180, 40, 140, 38))
        self.radioButtonPieceV2.setObjectName("radioButtonPieceV2")
        self.buttonGroupPiece.addButton(self.radioButtonPieceV2)
        self.radioButtonPieceV3 = QtWidgets.QRadioButton(self.groupBoxPiece)
        self.radioButtonPieceV3.setGeometry(QtCore.QRect(340, 40, 140, 38))
        self.radioButtonPieceV3.setObjectName("radioButtonPieceV3")
        self.buttonGroupPiece.addButton(self.radioButtonPieceV3)
        self.labelPieceV1 = QtWidgets.QLabel(self.groupBoxPiece)
        self.labelPieceV1.setGeometry(QtCore.QRect(20, 80, 100, 50))
        self.labelPieceV1.setText("")
        self.labelPieceV1.setPixmap(QtGui.QPixmap("../images/setting_dialog/piece_image_ver_1.png"))
        self.labelPieceV1.setObjectName("labelPieceV1")
        self.labelPieceV2 = QtWidgets.QLabel(self.groupBoxPiece)
        self.labelPieceV2.setGeometry(QtCore.QRect(180, 80, 100, 50))
        self.labelPieceV2.setText("")
        self.labelPieceV2.setPixmap(QtGui.QPixmap("../images/setting_dialog/piece_image_ver_2.png"))
        self.labelPieceV2.setObjectName("labelPieceV2")
        self.labelPieceV3 = QtWidgets.QLabel(self.groupBoxPiece)
        self.labelPieceV3.setGeometry(QtCore.QRect(340, 80, 100, 50))
        self.labelPieceV3.setText("")
        self.labelPieceV3.setPixmap(QtGui.QPixmap("../images/setting_dialog/piece_image_ver_3.png"))
        self.labelPieceV3.setObjectName("labelPieceV3")
        self.groupBoxRank = QtWidgets.QGroupBox(settingWindow)
        self.groupBoxRank.setGeometry(QtCore.QRect(10, 330, 490, 140))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK JP")
        self.groupBoxRank.setFont(font)
        self.groupBoxRank.setObjectName("groupBoxRank")
        self.radioButtonRankV0 = QtWidgets.QRadioButton(self.groupBoxRank)
        self.radioButtonRankV0.setGeometry(QtCore.QRect(20, 40, 140, 38))
        self.radioButtonRankV0.setObjectName("radioButtonRankV0")
        self.buttonGroupRank = QtWidgets.QButtonGroup(settingWindow)
        self.buttonGroupRank.setObjectName("buttonGroupRank")
        self.buttonGroupRank.addButton(self.radioButtonRankV0)
        self.radioButtonRankV1 = QtWidgets.QRadioButton(self.groupBoxRank)
        self.radioButtonRankV1.setGeometry(QtCore.QRect(180, 40, 140, 38))
        self.radioButtonRankV1.setObjectName("radioButtonRankV1")
        self.buttonGroupRank.addButton(self.radioButtonRankV1)
        self.radioButtonRankV2 = QtWidgets.QRadioButton(self.groupBoxRank)
        self.radioButtonRankV2.setGeometry(QtCore.QRect(340, 40, 140, 38))
        self.radioButtonRankV2.setObjectName("radioButtonRankV2")
        self.buttonGroupRank.addButton(self.radioButtonRankV2)
        self.labelRankV0 = QtWidgets.QLabel(self.groupBoxRank)
        self.labelRankV0.setGeometry(QtCore.QRect(20, 80, 100, 50))
        self.labelRankV0.setText("")
        self.labelRankV0.setPixmap(QtGui.QPixmap("../images/setting_dialog/rank_style_0.png"))
        self.labelRankV0.setObjectName("labelRankV0")
        self.labelRankV1 = QtWidgets.QLabel(self.groupBoxRank)
        self.labelRankV1.setGeometry(QtCore.QRect(180, 80, 100, 50))
        self.labelRankV1.setText("")
        self.labelRankV1.setPixmap(QtGui.QPixmap("../images/setting_dialog/rank_style_1.png"))
        self.labelRankV1.setObjectName("labelRankV1")
        self.labelRankV2 = QtWidgets.QLabel(self.groupBoxRank)
        self.labelRankV2.setGeometry(QtCore.QRect(340, 80, 100, 50))
        self.labelRankV2.setText("")
        self.labelRankV2.setPixmap(QtGui.QPixmap("../images/setting_dialog/rank_style_2.png"))
        self.labelRankV2.setObjectName("labelRankV2")
        self.pushButtonOK = QtWidgets.QPushButton(settingWindow)
        self.pushButtonOK.setGeometry(QtCore.QRect(80, 490, 128, 44))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK JP")
        self.pushButtonOK.setFont(font)
        self.pushButtonOK.setObjectName("pushButtonOK")
        self.pushButtonCancel = QtWidgets.QPushButton(settingWindow)
        self.pushButtonCancel.setGeometry(QtCore.QRect(270, 490, 128, 44))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK JP")
        self.pushButtonCancel.setFont(font)
        self.pushButtonCancel.setObjectName("pushButtonCancel")

        self.retranslateUi(settingWindow)
        QtCore.QMetaObject.connectSlotsByName(settingWindow)

    def retranslateUi(self, settingWindow):
        _translate = QtCore.QCoreApplication.translate
        settingWindow.setWindowTitle(_translate("settingWindow", "表示設定"))
        self.groupBoxBoard.setTitle(_translate("settingWindow", "将棋盤"))
        self.radioButtonBoardV1.setText(_translate("settingWindow", "将棋盤(白)"))
        self.radioButtonBoardV2.setText(_translate("settingWindow", "将棋盤(黄)"))
        self.groupBoxPiece.setTitle(_translate("settingWindow", "駒"))
        self.radioButtonPieceV1.setText(_translate("settingWindow", "二文字駒"))
        self.radioButtonPieceV2.setText(_translate("settingWindow", "一文字駒"))
        self.radioButtonPieceV3.setText(_translate("settingWindow", "英文字駒"))
        self.groupBoxRank.setTitle(_translate("settingWindow", "筋・段"))
        self.radioButtonRankV0.setText(_translate("settingWindow", "非表示"))
        self.radioButtonRankV1.setText(_translate("settingWindow", "標準"))
        self.radioButtonRankV2.setText(_translate("settingWindow", "Chess式"))
        self.pushButtonOK.setText(_translate("settingWindow", "OK"))
        self.pushButtonCancel.setText(_translate("settingWindow", "Cancel"))

